language: node_js

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE nsfwbuddy;" -U postgres
  - psql -c "CREATE USER nsfwbuddy WITH PASSWORD 'nsfwbuddy';" -U postgres

before_install:
  - yarn install

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - '8.5'

env:
  - JOB=test

script:
  - 'if [ "$JOB" = "test" ]; then make test; fi'
